version: "3.8"
services:
  mongo:
    image: mongo:latest
    container_name: tracking_mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - app_network

  fastapi:
    build: ./app
    container_name: fastapi
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
